config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :edit, :update] do
    member do
      get :reservations
      get :edit_account
      get :edit_profile
    end
  end
  get 'rooms/search', to: 'rooms#search', as: 'search_rooms'
  resources :rooms
  resources :reservations, only: [:show, :new, :create, :edit, :update, :index]
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :user_id, presence: true
  validates :room_id, presence: true
  validates :check_in, presence: true
  validates :check_out, presence: true
  validates :guests, presence: true

  validate :check_in_date_cannot_be_in_the_past
  validate :check_out_after_check_in
  validate :stay_at_least_one_night

  validates :guests, numericality: { greater_than_or_equal_to: 1, message: "At least one person" }

  def total_cost
    self.room.price * self.guests * ((self.check_out - self.check_in) / 86400).to_i
  end  

  private

  def check_in_date_cannot_be_in_the_past
    if check_in.present? && check_in < DateTime.now.end_of_day
      errors.add(:check_in, "can't be in the past")
    end
  end

  def check_out_after_check_in
    return if check_out.blank? || check_in.blank?

    if check_out < check_in
      errors.add(:check_out, "must be after the check in date")
    end
  end

  def stay_at_least_one_night
    if check_out == check_in
      errors.add(:check_out, "You should stay at least one night")
    end

    return if check_out.blank? || check_in.blank?
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :address, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 1 , message: "At least 1 yen" }
  scope :search, -> (search_term) { where('name LIKE ? OR description LIKE ?', "%#{search_term}%", "%#{search_term}%") if search_term.present? }
  scope :in_area, -> (area) { where('address LIKE ?', "%#{area}%") if area.present? }

  def index
    @rooms = Room.search(params[:query]).in_area(params[:area])
  end

  def self.search_by_area(area)
    if area.present?
      where('address LIKE ?', "%#{area}%")
    else
      all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :reservations

  validates :name, presence: true, on: :create
  validates :password, presence: true, on: :create

  has_many :rooms

  # Add this method
  def update_without_password(params, *options)
    params.delete(:password) if params[:password].blank?
    params.delete(:password_confirmation) if params[:password_confirmation].blank?

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  def avatar_url
    if avatar.attached?
      Rails.application.routes.url_helpers.rails_blob_path(avatar, only_path: true)
    else
      "https://rails-02-sample.herokuapp.com/assets/common/default-avatar-7a6cbfd7993e89f24bfc888f4a035a83c6f1428b8bdc47eed9095f2799a40153.png"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if params[:area]
      @rooms = Room.where("area LIKE ?", "%#{params[:area]}%")
    else
      @rooms = Room.all
    end
  end  
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update]
  before_action :authenticate_user!, only: [:create]

  def index
    if user_signed_in?
      @reservations = current_user.reservations
    else
      redirect_to new_user_session_path, notice: 'You need to sign in or sign up before continuing.'
    end
  end  
      
  def show
  end

  def new
    @room = Room.find(params[:room_id])
    @reservation = Reservation.new
  end

  def create
    puts "Current user: #{current_user.inspect}"
    @room = Room.find_by(id: params[:reservation][:room_id])
    if @room.nil?
      # Handle the case where the room doesn't exist
      redirect_to root_path, alert: 'Room not found.'
    else
      @reservation = Reservation.new(reservation_params)
      @reservation.user_id = current_user.id
      @reservation.room = @room
      if @reservation.save
        redirect_to @reservation, notice: 'Reservation was successfully created.'
      else
        puts @reservation.errors.full_messages
        render :new
      end
    end
  end

  def edit
  end

  def update
    if @reservation.update(reservation_params)
      redirect_to @reservation, notice: 'Reservation was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

  def reservation_params
    params.require(:reservation).permit(:room_id, :check_in, :check_out, :guests)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update]

  def index
    @rooms = Room.search(params[:search]).search_by_area(params[:area])
  end

  def show
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.user = current_user
    if @room.save
      redirect_to @room, notice: 'Room was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @room.update(room_params)
      redirect_to @room, notice: 'Room was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_room
    @room = Room.find_by(id: params[:id])
    redirect_to(rooms_path, alert: "Room not found.") unless @room
  end

  def room_params
    params.require(:room).permit(:name, :description, :price, :address, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit_account, :edit_profile, :update]
  before_action :set_user, only: [:show, :update]

  def index
    @reservations = current_user.reservations
  end
    
  def show
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def edit_account
    @user = current_user
  end
  

  def edit_profile
    @user = current_user
  end
  
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  def reservations
    @reservations = @user.reservations
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar).delete_if { |_, v| v.blank? }
  end
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">

  <title>Potepan Share</title>
  <style>
    .RecommendArea--tokyo {
      background-image: url(https://rails-02-sample.herokuapp.com//assets/home/recommend-area/tokyo.jpg);
    }
    .RecommendArea--osaka {
      background-image: url(https://rails-02-sample.herokuapp.com//assets/home/recommend-area/osaka.jpg);
    }
    .RecommendArea--kyoto {
      background-image: url(https://rails-02-sample.herokuapp.com//assets/home/recommend-area/kyoto.jpg);
    }
    .RecommendArea--sapporo {
      background-image: url(https://rails-02-sample.herokuapp.com//assets/home/recommend-area/sapporo.jpg);
    }
    .RecommendAreas {
      display: flex;
      justify-content: space-between;
      flex-wrap: wrap;
    }
    
    .RecommendArea {
      flex: 1 0 21%;  /* 4つの画像が横並びになるように調整 */
      margin: 1%;  /* 画像間のスペースを作る */
      background-size: cover;
      background-position: 50%;
      border-radius: 26px;
      display: flex;
      flex-direction: column;
      height: 455px;
      justify-content: flex-end;
      padding: 40px 24px;
    }
    
    .RecommendArea img {
      width: 100%;
      height: auto;
    }
  </style>
</head>
<body>
  <h1 class="text-center mt-5">Potepan Shareでまだ体験したことのない旅をしよう</h1>

  <div class="container">
    <%= form_with(url: rooms_path, method: :get, local: true) do %>
      <%= text_field_tag :query, params[:query] %>
      <%= submit_tag "Search by accomodation name", name: nil %>
    <% end %>

    <h2 class="RecommendAreaSection__title">
      おすすめのエリア
    </h2>

    <%= form_with(url: rooms_path, method: :get, local: true) do |form| %>
      <%= form.label :area, '' %>
      <%= form.text_field :area %>
      <%= form.submit 'Search by address' %>
    <% end %>    
  </div>

  <footer class="footer mt-auto py-3 bg-light">
    <div class="container text-center">
      <span class="text-muted">Copyright © Potepan Share 2023 All rights reserved</span>
    </div>
  </footer>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <div class="RecommendAreas">
    <a class="RecommendArea RecommendArea--tokyo" href="/rooms?area=東京">
      <img alt="Tokyo">
      <span class="RecommendArea__name RecommendArea__name--en">Tokyo</span>
    </a>
    <a class="RecommendArea RecommendArea--osaka" href="/rooms?area=大阪">
      <img alt="Osaka">
      <span class="RecommendArea__name RecommendArea__name--en">Osaka</span>
    </a>
    <a class="RecommendArea RecommendArea--kyoto" href="/rooms?area=京都">
      <img alt="Kyoto">
      <span class="RecommendArea__name RecommendArea__name--en">Kyoto</span>
    </a>
    <a class="RecommendArea RecommendArea--sapporo" href="/rooms?area=札幌">
      <img alt="Sapporo">
      <span class="RecommendArea__name RecommendArea__name--en">Sapporo</span>
    </a>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReservationApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


    <style>
      header {
        background-color: #1c1d3b;
        height: 80px;
        padding-bottom: 50px;
      }
      .Navbar {
        height: 80px;
      }
      .Navbar__logo {
        width: 221px;
      }
      .NavProfile__avatar {
        border-radius: 60px;
        margin-right: 8px;
        width: 40px;
      }
    </style>
  </head>

  <body>
    <header>
      <nav class="navbar Navbar">
        <div class="container-fluid">
          <a href="/"><img class="Navbar__logo" alt="サイトロゴ" src="https://rails-02-sample.herokuapp.com/assets/common/logo.png"></a>
          <% if user_signed_in? %>
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle " type="button" id="dropdown-button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= image_tag current_user.avatar_url, class: 'NavProfile__avatar', alt: 'アバター' if current_user.avatar_url.present? %>
                <span class="nav-item d-sm-inline-block d-none NavProfile__name">
                  <%= current_user.name %>
                </span>
              </button>

              <ul class="dropdown-menu" aria-labelledby="dropdown-button">
                <li><%= link_to '施設の新規登録', new_room_path, class: 'dropdown-item' %></li>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to '予約済み一覧', reservations_path, class: 'dropdown-item' %></li>
                <li><%= link_to '登録済み一覧', rooms_path, class: 'dropdown-item' %></li>
                <li><%= link_to 'アカウント設定', edit_account_user_path(current_user), class: 'dropdown-item' %></li>
                <li><%= link_to 'プロフィール設定', edit_profile_user_path(current_user), class: 'dropdown-item' %></li>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'dropdown-item' %></li>
              </ul>
            </div>
          <% else %>
            <%= link_to 'ログイン', new_user_session_path, class: 'nav-link' %>
            <%= link_to '新規登録', new_user_registration_path, class: 'nav-link' %>
          <% end %>
        </div>
      </nav>
    </header>

    <%= yield %>
  </body>
</html>

app/views/reservations/edit.html.erb
<%= form_for(@reservation) do |f| %>
    <%= f.label :check_in %>
    <%= f.date_field :check_in %>
  
    <%= f.label :check_out %>
    <%= f.date_field :check_out %>
  
    <%= f.label :guests %>
    <%= f.number_field :guests %>
  
    <%= f.submit "Update Reservation" %>
  <% end %>
  

app/views/reservations/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Image</th>
      <th>Room Name</th>
      <th>Description</th>
      <th>Check In</th>
      <th>Check Out</th>
      <th>Nights</th>
      <th>Guests</th>
      <th>Total Cost</th>
      <th>Confirmed At</th>
    </tr>
  </thead>
  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td>
          <% if reservation.room.image.attached? %>
            <%= image_tag(reservation.room.image.variant(resize: "100x100"), class: "img-fluid") %>
          <% else %>
            <%= image_tag("https://rails-02-sample.herokuapp.com/assets/room/default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png", size: "100x100", class: "img-fluid") %>
          <% end %>
        </td>
        <td><%= reservation.room.name %></td>
        <td><%= reservation.room.description %></td>
        <td><%= reservation.check_in.strftime("%Y/%m/%d") %></td>
        <td><%= reservation.check_out.strftime("%Y/%m/%d") %></td>
        <td><%= ((reservation.check_out - reservation.check_in) / 86400).to_i %></td>
        <td><%= reservation.guests %></td>
        <td><%= reservation.total_cost %></td>
        <td><%= reservation.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reservations/new.html.erb
<div class="container">
  <%= form_for(@reservation, html: { class: 'form-horizontal' }) do |f| %>
    <div class="form-group">
      <%= f.hidden_field :room_id, value: @room.id %>
    </div>

    <div class="form-group">
      <%= f.label :check_in, class: 'control-label' %>
      <%= f.date_field :check_in, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :check_out, class: 'control-label' %>
      <%= f.date_field :check_out, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :guests %>
      <%= f.number_field :guests, class: 'form-control', required: true, min: 1, oninput: "validity.valid||(value='');" %>
      <div class="invalid-feedback">
        Number of guests must be a positive number.
      </div>
    </div>

    <div class="form-group">
      <%= f.submit "Reserve", class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/reservations/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Reservation Details</h5>

          <p class="card-text">
            <strong>Number of nights:</strong>
            <%= ((@reservation.check_out - @reservation.check_in) / 86400).to_i %>
          </p>

          <p class="card-text">
            <strong>Number of guests:</strong>
            <%= @reservation.guests %>
          </p>

          <p class="card-text">
            <strong>Total cost:</strong>
            <%= @reservation.total_cost %>
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-md-12">
      <%= link_to '戻る', request.referer, class: "btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/rooms/create.html.erb
<h1>Rooms#create</h1>
<p>Find me in app/views/rooms/create.html.erb</p>

app/views/rooms/edit.html.erb
<div class="container">
  <h1 class="my-4">Edit Room</h1>

  <%= form_for(@room, html: { class: 'needs-validation', novalidate: true }) do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', required: true %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control', required: true %>
    </div>

    <div class="form-group">
      <%= f.label :price %>
      <%= f.number_field :price, class: 'form-control', required: true %>
    </div>

    <div class="form-group">
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control', required: true %>
    </div>

    <div class="form-group">
      <%= f.label :image %>
      <%= f.file_field :image, class: 'form-control-file', id: 'room_image' %>
      <img id="img" accept="image/*" src="https://rails-02-sample.herokuapp.com/assets/common/default-avatar-7a6cbfd7993e89f24bfc888f4a035a83c6f1428b8bdc47eed9095f2799a40153.png" style="display: none;">
    </div>

    <%= f.submit "Update Room", class: 'btn btn-primary' %>
  <% end %>

  <%= link_to 'Back', user_path(@room.user), class: 'btn btn-secondary mt-3' %>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script>
$(document).on('turbolinks:load', function() {
  $('#room_image').on('change', function (e) {
      var reader = new FileReader();
      reader.onload = function (e) {
          $("#img").attr('src', e.target.result);
          $("#img").css('display', '');
      }
      reader.readAsDataURL(e.target.files[0]);
  });

  // 削除ボタンクリック時にフォームとプレビューを初期化
  $('#delete').on('click', function (e) {
    $("#img").attr('src', '');
    $("#form").val('');
  });
});
</script>

app/views/rooms/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Image</th>
      <th>Room Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Created At</th>
      <th>Actions</th> <!-- Add this if it doesn't exist -->
    </tr>
  </thead>
  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td>
          <% if room.image.attached? %>
            <%= image_tag(room.image.variant(resize: "100x100"), class: "img-fluid") %>
          <% else %>
            <%= image_tag("https://rails-02-sample.herokuapp.com/assets/room/default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png", size: "100x100", class: "img-fluid") %>
          <% end %>
        </td>
        <td><%= link_to room.name, room_path(room) %></td>
        <td><%= room.description %></td>
        <td><%= room.price %>/day</td>
        <td><%= room.created_at.to_date %></td>
        <td>
          <% if current_user == room.user %>
            <%= link_to 'Edit', edit_room_path(room), class: 'btn btn-primary' %>
          <% end %>
          <%= link_to 'Book', new_reservation_path(room_id: room.id), class: 'btn btn-success' %> <!-- Replace with your booking path -->
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rooms/search.html.erb
<div class="container">
  <h1 class="text-center">Search Results</h1>

  <p class="text-center">Total rooms found: <%= @rooms.count %></p>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Address</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <% @rooms.each do |room| %>
        <tr>
          <td><%= link_to room.name, room_path(room) %></td>
          <td><%= room.description %></td>
          <td><%= room.address %></td>
          <td><%= room.price %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% if user_signed_in? %>
    <%= link_to 'Back', user_path(current_user), class: 'btn btn-primary' %>
  <% else %>
    <%= link_to 'Back', rooms_path, class: 'btn btn-primary' %>
  <% end %>

</div>

app/views/rooms/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-9">
      <h2><strong>Name:</strong> <%= @room.name %></h2>
      <p><strong>Description:</strong> <%= @room.description %></p>
      <p><strong>Price/Day:</strong> <%= @room.price %></p>
      <p><strong>Address:</strong> <%= @room.address %></p>
    </div>
  </div>
    <div class="row mt-3">
      <div class="col-md-12">
        <% if current_user == @room.user %>
          <%= link_to '編集する', edit_room_path(@room), class: "btn btn-primary" %>
        <% end %>
        <%= link_to '戻る', request.referer || root_path, class: "btn btn-secondary" %>
      </div>
    </div>
</div>

app/views/users/edit_account.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= form_for @user, url: user_path(@user) do |f| %>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>

        <%= f.submit 'Update Account', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit_profile.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= form_for @user, url: user_path(@user), html: { multipart: true } do |f| %>
        <div class="form-group">
          <%= f.label :avatar %>
          <%= f.file_field :avatar, class: 'form-control', id: 'user_avatar' %>
          <img id="img" accept="image/*" src="https://rails-02-sample.herokuapp.com/assets/common/default-avatar-7a6cbfd7993e89f24bfc888f4a035a83c6f1428b8bdc47eed9095f2799a40153.png" style="display: none;">
        </div>

        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :introduction %>
          <%= f.text_area :introduction, class: 'form-control' %>
        </div>

        <%= f.submit 'Update Profile', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script>
$(document).on('turbolinks:load', function() {
  $('#user_avatar').on('change', function (e) {
      var reader = new FileReader();
      reader.onload = function (e) {
          $("#img").attr('src', e.target.result);
          $("#img").css('display', '');
      }
      reader.readAsDataURL(e.target.files[0]);
  });

  // 削除ボタンクリック時にフォームとプレビューを初期化
  $('#delete').on('click', function (e) {
    $("#img").attr('src', '');
    $("#form").val('');
  });
});
</script>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
  
    <%= f.label :email %>
    <%= f.email_field :email %>
  
    <%= f.label :password %>
    <%= f.password_field :password %>
  
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  
    <%= f.submit "Sign up" %>
  <% end %>
  

app/views/users/reservations.html.erb
<h1>Your Reservations</h1>

<% @reservations.each do |reservation| %>
  <div>
    <h2><%= link_to reservation.room.name, room_path(reservation.room) %></h2>
    <p><%= reservation.room.description %></p>
    <p>Total Price/Day: <%= reservation.room.price * (reservation.check_out - reservation.check_in).to_i %></p>
    <p>Check-in: <%= reservation.check_in.strftime("%Y/%m/%d") %></p>
    <p>Check-out: <%= reservation.check_out.strftime("%Y/%m/%d") %></p>
    <p>Reservation Date: <%= reservation.created_at.strftime("%Y/%m/%d %H:%M") %></p>
    <%= image_tag reservation.room.image.variant(resize: "500x500"), default_url: "https://rails-02-sample.herokuapp.com/assets/common/default-avatar-7a6cbfd7993e89f24bfc888f4a035a83c6f1428b8bdc47eed9095f2799a40153.png" if reservation.room.image.attached? %>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="text-center">
        <% if @user.avatar.attached? %>
          <%= image_tag @user.avatar.variant(resize: "50x50"), class: "rounded-circle" %>
        <% else %>
          <%= image_tag "https://rails-02-sample.herokuapp.com/assets/common/default-avatar-7a6cbfd7993e89f24bfc888f4a035a83c6f1428b8bdc47eed9095f2799a40153.png", size: "50x50", class: "rounded-circle" %>
        <% end %>
      </div>

      <div class="mt-3">
        <h4><strong>Name:</strong> <%= @user.name %></h4>
        <p>Email: <%= @user.email %></p>
        <p>Password: ********</p>
      </div>
      
      <div class="mt-3">
        <h2>登録した宿泊施設</h2>
        <table class="table">
          <thead>
            <tr>
              <th>宿泊施設名</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @user.rooms.each do |room| %>
              <tr>
                <td><%= link_to room.name, room_path(room) %></td>
                <td><%= link_to '編集', edit_room_path(room), class: "btn btn-info" %></td>
                <td><%= link_to '予約', new_reservation_path(room_id: room.id), class: "btn btn-primary" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="mt-3">
        <h2>
          <%= link_to '予約確認', reservations_path, class: "btn btn-warning" %>
        </h2>
      </div>
    </div>
  </div>
</div>